---
title: "Age norming example: effects on mean and dispersion"
output:
  html_document:
    df_print: paged
    toc: true
date: "`r format(Sys.time(), '%d %B, %Y')`"
editor_options: 
  chunk_output_type: console
---

# Init

```{r}
library(kirkegaard)
load_packages(
  
)

theme_set(theme_bw())

options(
    digits = 3
)

#multithreading
#library(future)
#plan(multisession(workers = 8))
```

# Example

```{r}
#simulate some data, mess up the norms, and get them back
set.seed(1)
data = tibble(
 true_IQ = c(rnorm(1000, mean = 100, sd = 15), rnorm(1000, mean = 90, sd = 15)),
 true_z = (true_IQ - 100 ) / 15,
 age = runif(2000, min = 18, max = 80),
 norm_group = c(rep(T, 1000), rep(F, 1000))
 ) %>% mutate(
 #add an effect of age on the mean and dispersion of scores
 age_mean_effect = age * 0.3 - 0.3 * 18,
 age_sd_effect = true_z * 15 * rescale(age, new_min = .80, new_max = 1.20),
 score = 100 + age_sd_effect + age_mean_effect
 )

#add some missing data too
data = data %>% miss_add_random(prop = .05)

#restore the norms
norms = make_norms(data$score, data$age, data$norm_group)
data$IQ = norms$data$IQ

#manually apply norms
data$IQ2 = apply_norms(data$score, data$age, prior_norms = norms)
data$IQ3 = apply_norms(data$score, data$age,
age_model_slope = norms$age_model$coefficients[2],
age_model_intercept = norms$age_model$coefficients[1],
age_model_abs_slope = norms$age_model_abs$coefficients[2],
age_model_abs_intercept = norms$age_model_abs$coefficients[1],
mean = norms$norm_desc$mean,
sd = norms$norm_desc$sd
)

#verify that scores were made correct
wtd.cors(data)
GG_scatter(data, "age", "score")

#do we get all the scores we can get?
data %>% miss_by_var(reverse = T)
data %>% select(score, age) %>% miss_filter() %>% nrow()
#yes, same cases number for score + age and IQ

#can we detect the age heteroscedasticity too?
#yes, and it's linear as we expect
test_HS(resid = resid(lm(score ~ age, data = data)), x = data$age)

#plot the results
GG_scatter(data, "true_IQ", "score") + geom_abline(slope = 1, intercept = 0, linetype = 2)
GG_scatter(data, "true_IQ", "IQ") + geom_abline(slope = 1, intercept = 0, linetype = 2)

```


# Meta

```{r}
#versions
write_sessioninfo()
```
